language: python
python:
  - 3.7
  - 3.6
  - 3.5

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

git:
    submodules: false

install:
  - pip install .

script: python -m unittest discover -v
